import Head from "next/head";
import styles from "../styles/Home.module.css";
import AudioList from "../components/AudioList";
import { supabase } from "../lib/supabaseClient";
import { AUDIOS_TABLE } from "../lib/consts";

export default function Home({ audios }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Web Audio Player</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.audioContainer}>
          <AudioList audios={audios} />
        </div>
      </main> 
    </div>
  );
}

export async function getServerSideProps(context) {
  const { data: audios, error } = await supabase
    .from(AUDIOS_TABLE)
    .select("created_at, title, filename")
    .order("created_at", { ascending: false });
  return {
    props: { audios: error ? [] : audios },
  };
}
